name: Build and Deploy
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.*'
  pull_request:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: cat ~/.m2/settings.xml

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test with Maven
        run: mvn -B compile test

      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1

      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/v') # only tagged releases starting with a v will run this action
        uses:  usethesource/releases-maven-action@v1
        with:
          maven-username: ${{ secrets.MAVEN_USERNAME }}
          maven-password: ${{ secrets.MAVEN_PASSWORD }}
          maven-local-port: ${{ secrets.MAVEN_WEBDAV_PORT }}
          ssh-hostname: ${{ secrets.SSH_SERVER }}
          ssh-known-host: ${{ secrets.SSH_KNOWN_HOSTS }}
          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}



      - name: Attach artifact
        id: build-artifact
        uses:  SWAT-engineering/maven-full-artifacts-action@v1

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: ${{ steps.build-artifact.outputs.artifact-root-dir}}/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}