name: Build and Deploy
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.*'
  pull_request:
    branches:
      - main
    

env:
  MAVEN_OPTS: "-Xmx4G -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: m2

      - name: Compile and Typechek 
        run: mvn -B compile

      - name: Test
        run: mvn -B test

      - name: Publish Test Report on github action
        if: ${{ always() && github.event_name != 'pull_request' }} # to bad this doesn't work nicely with external pull requests
        uses: scacap/action-surefire-report@v1
        with:
          check_name: "Test Report"

      - name: cleanup tests to reduce jar size
        run: |
          rm -r src/examples
          rm -r target/classes/examples
      - name: Attach artifact
        id: build-artifact
        uses: SWAT-engineering/maven-full-artifacts-action@v1.4-rc1